mod.mc_dep_forgelike=[26.3, 26.4)
deps.minecraft=26.3

deps.neoforge=26.3.0.26-beta
deps.yacl=3.9.7+26.3-neoforge
deps.rrv=8.10.9+26.3
deps.item_descriptions=2.8.4+26.2-neoforge
deps.reliable_remover=3.3.0+26.3-neoforge
deps.etf=7.2.4-neoforge-26.3
deps.emf=3.3.8-neoforge-26.3
deps.scholar=yZo75m3Z
