# Project
version=1.7.5
group=com.evandev.fieldguide
java_version=17

# Common
minecraft_version=1.20.1
mod_name=Field Guide
mod_author=Evan, Kobber
mod_id=fieldguide
license=MIT
credits=Additional textures by Nekomaster!
description=Discover Plants, Animals, and Monsters with a Spyglass. Collect them all and take notes in your personal Field Guide!
minecraft_version_range=[1.20.1, 1.20.2)

# Parchment
parchment_minecraft=1.20.1
parchment_version=2023.09.03

# Optional Dependencies
cloth_config_version=11.1.118
mod_menu_version=7.2.2
emi_version=1.0.4+1.20.1
item_descriptions_version=2.5.4+1.20.1
kaleido_config_version=0.3.3+1.3.2
immersive_overlays_version=1.4.2+1.20.1
spyglass_improvements_forge_version=1.5.12b+mc1.20
spyglass_improvements_fabric_version=1.5.12+mc1.20.1
reliable_remover_version=1.5.1
etf_version=7.0.6
emf_version=3.0.12
exposure_forge_version=1FNjyOaJ
exposure_fabric_version=YNAcmTj6
fcapi_version=v8.0.3-1.20.1
cobblemon_version=1.5.2+1.20.1
kubejs_forge_version=g5igndAv
kubejs_fabric_version=kPLHkyoJ
serene_seasons_forge_version=YXTfAkOf
serene_seasons_fabric_version=c1BdjabH
fabric_seasons_version=2.4.2-BETA+1.20
ecliptic_seasons_version=G4OHOTAz

# Fabric
fabric_version=0.92.1+1.20.1
fabric_loader_version=0.16.9

# Forge
forge_version=47.3.0
forge_loader_version_range=[47,)

# Gradle
org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false
org.gradle.vfs.watch=true