plugins {
    id 'multiloader-loader'
    id 'net.neoforged.moddev.legacyforge'
}

mixin {
    add(sourceSets.main, "${mod_id}.refmap.json")

    config("${mod_id}.mixins.json")
    config("${mod_id}.forge.mixins.json")
}

legacyForge {
    version = "${minecraft_version}-${forge_version}"

    def at = project(':common').file('src/main/resources/META-INF/accesstransformer.cfg')
    if (at.exists()) {
        accessTransformers.from(at)
    }

    parchment {
        minecraftVersion = parchment_minecraft
        mappingsVersion = parchment_version
    }

    runs {
        client {
            client()
        }
        server {
            server()
        }
    }

    mods {
        "${mod_id}" {
            sourceSet sourceSets.main
            sourceSet project(":common").sourceSets.main
        }
    }
}

sourceSets.main.resources.srcDir 'src/generated/resources'

dependencies {
    compileOnly 'org.jetbrains:annotations:26.0.2-1'

    // Item Descriptions
    modImplementation "maven.modrinth:item-descriptions:${item_descriptions_version}-forge"

    // EMI
    modImplementation "dev.emi:emi-forge:${emi_version}"

    // Cloth Config
    modImplementation "me.shedaniel.cloth:cloth-config-forge:${cloth_config_version}"

    // Immersive Overlays
    modRuntimeOnly "maven.modrinth:immersive-overlays:${immersive_overlays_version}-forge"

    // Spyglass Improvements
    modRuntimeOnly "maven.modrinth:spyglass-improvements:${spyglass_improvements_forge_version}+forge"

    // ETF/EMF
    modCompileOnly "maven.modrinth:entitytexturefeatures:${etf_version}-forge-1.20.1"
    modCompileOnly "maven.modrinth:entity-model-features:${emf_version}-forge-1.20.1"

    // Reliable Remover
    modCompileOnly "maven.modrinth:reliable-remover:${reliable_remover_version}-forge-1.20.1"

    // Exposure
    // This crashes in dev for some reason
    modCompileOnly "maven.modrinth:exposure:${exposure_forge_version}"

    // Cobblemon
    modCompileOnly "com.cobblemon:forge:${cobblemon_version}"

    // KubeJS
    modCompileOnly "maven.modrinth:kubejs:${kubejs_forge_version}"

    // Serene Seasons
    modCompileOnly "maven.modrinth:serene-seasons:${serene_seasons_forge_version}"
    //modRuntimeOnly "maven.modrinth:serene-seasons:${serene_seasons_forge_version}"
    //modRuntimeOnly "maven.modrinth:glitchcore:0.0.1.1"

    // Ecliptic Seasons
    modRuntimeOnly "maven.modrinth:ecliptic-seasons:${ecliptic_seasons_version}"

    // Dawn Era
    modCompileOnly "maven.modrinth:the-dawn-era:0.642"
    modCompileOnly "maven.modrinth:astemirlib:1.25"

    // Scholar
    modImplementation "maven.modrinth:scholar:yxQA51K6"

    // Curios
    modImplementation "maven.modrinth:curios:5.14.1+1.20.1"

    compileOnly project(":common")
    annotationProcessor("org.spongepowered:mixin:0.8.5-SNAPSHOT:processor")
}

jar {
    finalizedBy('reobfJar')
    manifest.attributes([
            "MixinConfigs": "${mod_id}.mixins.json,${mod_id}.forge.mixins.json"
    ])
}

publishMods {
    file = tasks.named("reobfJar").flatMap { it.archiveFile }
}
