mod.mc_dep_forgelike=[1.21.1, 1.21.2)
deps.minecraft=1.21.1
publish.additionalVersions=1.21

deps.java_version=21
deps.parchment=2024.11.17
deps.neoforge=21.1.226
deps.yacl=3.8.1+1.21.1-neoforge
deps.emi=1.1.22+1.21.1
deps.item_descriptions=2.8.0+1.21.1-neoforge
deps.immersive_overlays=1.7.5+1.21.1-neoforge
deps.reliable_remover=3.2.0-1.21.1-neoforge
deps.etf=7.2.1-neoforge-1.21
deps.emf=3.3.2-neoforge-1.21
deps.exposure=WYaaE1QE
deps.no_mans_land=1.5.11
deps.biolith=xaeaSA9Q
deps.cobblemon=1.7.3+1.21.1
deps.mixed_litter=1.2.2
deps.primal=bjAno6mP
deps.kubejs=8nuqyxbw
deps.rhino=2101.2.7-build.81
deps.serene_seasons=SPj5bJoM
deps.scholar=t5aJhKGV
