mod.mc_dep_fabric=~26.2
deps.minecraft=26.2

deps.fabric_api=0.161.0+26.2
deps.modmenu=20.0.3
deps.yacl=3.9.7+26.2-fabric
deps.rrv=8.10.9+26.2
deps.item_descriptions=2.8.4+26.2-fabric
deps.immersive_overlays=1.8.5+26.2-fabric
deps.mru=1.0.40+26.2-fabric
deps.spyglass_improvements=1.5.14+mc26.2+fabric
deps.reliable_remover=3.3.2-26.2-fabric
deps.etf=7.2.4-fabric-26.2
deps.emf=3.3.8-fabric-26.2
deps.scholar=Heqwkz9Z
