mod.mc_dep_forgelike=[26.1, 26.2)
deps.minecraft=26.1.2
publish.additionalVersions=26.1,26.1.1

deps.neoforge=26.1.2.112
deps.yacl=3.9.7+26.1-neoforge
deps.rrv=8.10.9+26.1.2
deps.item_descriptions=2.8.4+26.1.2-neoforge
deps.immersive_overlays=1.8.5+26.1.2-neoforge
deps.reliable_remover=3.3.0+26.1.2-neoforge
deps.etf=7.2.4-neoforge-26.1
deps.emf=3.3.8-neoforge-26.1
deps.kubejs=FzLyIIBB
deps.rhino=2101.2.8-build.91
deps.scholar=MzMe1NNq
