mod.mc_dep_forgelike=[26.2, 26.3)
deps.minecraft=26.2

deps.neoforge=26.2.0.88
deps.yacl=3.9.7+26.2-neoforge
deps.rrv=8.10.9+26.2
deps.item_descriptions=2.8.4+26.2-neoforge
deps.immersive_overlays=1.8.5+26.2-neoforge
deps.reliable_remover=3.3.0+26.2-neoforge
deps.etf=7.2.4-neoforge-26.2
deps.emf=3.3.8-neoforge-26.2
deps.scholar=yZo75m3Z
