mod.mc_dep_fabric=~1.21.1
deps.minecraft=1.21.1
publish.additionalVersions=1.21

deps.java_version=21
deps.parchment=2024.11.17
deps.fabric_api=0.116.7+1.21.1
deps.modmenu=11.0.3
deps.yacl=3.8.1+1.21.1-fabric
deps.emi=1.1.22+1.21.1
deps.item_descriptions=2.8.0+1.21.1-fabric
deps.kaleido_config=0.3.3+1.3.2
deps.immersive_overlays=1.7.5+1.21.1-fabric
deps.mru=1.0.40+1.21.1-fabric
deps.spyglass_improvements=1.5.7+mc1.21+fabric
deps.reliable_remover=3.3.0+1.21.1-fabric
deps.etf=7.2.1-fabric-1.21
deps.emf=3.3.2-fabric-1.21
deps.exposure=EDtO2y84
deps.fcapi=v21.1.6-1.21.1-Fabric
deps.night_config=3.8.0
deps.no_mans_land=1.5.11
deps.cobblemon=1.7.3+1.21.1
deps.serene_seasons=UqA7miTT
deps.fabric_seasons=2.4.2-BETA+1.21
deps.scholar=MpMbLKGR
