plugins {
    id 'multiloader-loader'
    id 'net.neoforged.moddev'
}

neoForge {
    version = neoforge_version
    def at = project(':common').file('src/main/resources/META-INF/accesstransformer.cfg')
    if (at.exists()) {
        accessTransformers.from(at.absolutePath)
    }

    runs {
        configureEach {
            systemProperty('neoforge.enabledGameTestNamespaces', mod_id)
            ideName = "NeoForge ${it.name.capitalize()} (${project.path})"
        }
        client {
            client()
            gameDirectory = this.mkdir(this.file("runs/client"))
        }
        data {
            clientData()
            gameDirectory = this.mkdir(this.file("runs/data"))
            programArguments.addAll '--mod', project.mod_id, '--all', '--output', file('src/generated/resources/').getAbsolutePath(), '--existing', file('src/main/resources/').getAbsolutePath()
        }
        server {
            server()
            this.file("runs/server").createParentDirectories()
            gameDirectory = this.mkdir(this.file("runs/server"))
        }
    }

    mods {
        "${mod_id}" {
            sourceSet sourceSets.main
        }
    }
}

sourceSets.main.resources.srcDir 'src/generated/resources'

dependencies {
    // Item Descriptions
    implementation "maven.modrinth:item-descriptions:${item_descriptions_version}-neoforge"

    // RRV
    runtimeOnly("cc.cassian.rrv:reliable-recipe-viewer-neoforge:${rrv_version}")

    // YACL
    implementation "dev.isxander:yet-another-config-lib:${yacl_version}-neoforge"

    // Immersive Overlays
    //runtimeOnly "maven.modrinth:immersive-overlays:${immersive_overlays_version}-neoforge"

    // Spyglass Improvements
    //runtimeOnly "maven.modrinth:spyglass-improvements:${spyglass_improvements_version}+neoforge"

    // ETF & EMF
    compileOnly "maven.modrinth:entitytexturefeatures:${etf_version}-neoforge-26.2"
    compileOnly "maven.modrinth:entity-model-features:${emf_version}-neoforge-26.2"

    // Reliable Remover
    compileOnly "maven.modrinth:reliable-remover:${reliable_remover_version}-neoforge"

    // Exposure
    //implementation "maven.modrinth:exposure:${exposure_neoforge_version}"

    // Mixed Litter
    //compileOnly "maven.modrinth:mixed-litter:${mixed_litter_version}"

    // Cobblemon
    //compileOnly "com.cobblemon:neoforge:${cobblemon_version}"

    // KubeJS
    //compileOnly "maven.modrinth:kubejs:${kubejs_version}"

    // Serene Seasons
    //compileOnly "maven.modrinth:serene-seasons:${serene_seasons_neoforge_version}"
    //runtimeOnly "maven.modrinth:serene-seasons:${serene_seasons_neoforge_version}"
    //runtimeOnly "maven.modrinth:glitchcore:8wmCpbQ2"

    // Ecliptic Seasons
    //runtimeOnly "maven.modrinth:ecliptic-seasons:${ecliptic_seasons_version}"

    // Scholar
    //implementation "maven.modrinth:scholar:t5aJhKGV"
}

publishMods {
    file = tasks.named("jar").flatMap { it.archiveFile }
}
