mod.mc_dep_forgelike=[1.20.1, 1.20.2)
deps.minecraft=1.20.1

deps.java_version=17
deps.parchment=2023.09.03
deps.forge=47.4.10
deps.yacl=3.6.6+1.20.1-forge
deps.emi=1.1.24+1.20.1
deps.item_descriptions=2.5.4+1.20.1-forge
deps.immersive_overlays=1.8.5+1.20.1-forge
deps.spyglass_improvements=1.5.12b+mc1.20+forge
deps.reliable_remover=3.1.0-1.20.1-forge
deps.etf=7.2.1-forge-1.20.1
deps.emf=3.3.2-forge-1.20.1
deps.exposure=ob6nJLBU
deps.cobblemon=1.5.2+1.20.1
deps.kubejs=g5igndAv
deps.serene_seasons=YXTfAkOf
deps.ecliptic_seasons=G4OHOTAz
deps.dawn_era=0.642
deps.astemirlib=1.25
deps.scholar=DxJo8Kc6
deps.rhino=2001.2.3-build.10
deps.quark=1.20.1-4.0-462
deps.zeta=1.20.1-1.0-31
